### PR TITLE
You challanged me to make a help cmd, SO HERE YOU ARE.

### PR DESCRIPTION
**Pull request by AnmolPlayzz**

### CODE REVIEW

**Comment by Not-Jayy** [comment]
jit wasn't playin'

**Comment by AnmolPlayzz** [comment]
jit ?!?!?!

**Comment by Not-Jayy** [comment]
> jit ?!?!?!

think of it as me saying bro, this is very nice tho icl thanks homie very cool 😎

**Comment by AnmolPlayzz** [comment]
ahhh
wlcm my guy :))))

**Pull request merged**
